In [27]:
import yfinance as yf

In [39]:
ticker = yf.Ticker("QQQ")

In [41]:
ticker.info['priceHint']

2

In [42]:
ticker.news

[{'id': '237c7d98-97e3-362d-8968-719f8aac5be7',
  'content': {'id': '237c7d98-97e3-362d-8968-719f8aac5be7',
   'contentType': 'STORY',
   'title': 'What Actually Drove IWD Over The Past Year',
   'description': '',
   'summary': "The fund's strong return hides a story of extreme concentration, with a few winners pulling the weight for hundreds of others.",
   'pubDate': '2026-07-03T12:55:34Z',
   'displayTime': '2026-07-03T12:55:34Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/trefis_142/56c363bffa73f8b8cfa9cd71fae1de1c',
    'originalWidth': 1280,
    'originalHeight': 869,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/nmtFbJBZ44Vt9xFgQaOr9w--~B/aD04Njk7dz0xMjgwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/trefis_142/56c363bffa73f8b8cfa9cd71fae1de1c',
      'width': 1280,
      'height': 869,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/NQkaffIFgkkzaCZDVMiY3w--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/trefis_142/56c363bffa73f8b8cfa9cd71fae1de1c',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Trefis',
    'url': 'https://www.trefis.com/',
    'sourceId': 'trefis_142'},
   'canonicalUrl': {'url': 'https://www.trefis.com/articles/605699/what-actually-drove-iwd-over-the-past-year/2026-07-03',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/actually-drove-iwd-over-past-125534583.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '6e6b5174-8429-3b69-985f-57f39c65bb4a',
  'content': {'id': '6e6b5174-8429-3b69-985f-57f39c65bb4a',
   'contentType': 'STORY',
   'title': "EWY's Dip Looks Familiar, But Is It A Trap?",
   'description': '',
   'summary': 'The South Korea ETF has a habit of bouncing back from drops like this one, but the price of admission has often been more pain.',
   'pubDate': '2026-07-03T12:55:05Z',
   'displayTime': '2026-07-03T12:55:05Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/trefis_142/56c363bffa73f8b8cfa9cd71fae1de1c',
    'originalWidth': 1280,
    'originalHeight': 869,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/nmtFbJBZ44Vt9xFgQaOr9w--~B/aD04Njk7dz0xMjgwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/trefis_142/56c363bffa73f8b8cfa9cd71fae1de1c',
      'width': 1280,
      'height': 869,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/NQkaffIFgkkzaCZDVMiY3w--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/trefis_142/56c363bffa73f8b8cfa9cd71fae1de1c',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Trefis',
    'url': 'https://www.trefis.com/',
    'sourceId': 'trefis_142'},
   'canonicalUrl': {'url': 'https://www.trefis.com/articles/605701/ewys-dip-looks-familiar-but-is-it-a-trap/2026-07-03',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/ewys-dip-looks-familiar-trap-125505066.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '731b8e42-9c02-3e58-85a7-158f84d90045',
  'content': {'id': '731b8e42-9c02-3e58-85a7-158f84d90045',
   'contentType': 'STORY',
   'title': 'Should You Buy the Invesco QQQ ETF After the Recent Nasdaq Sell-Off? History Offers a Crystal-Clear Answer.',
   'description': '',
   'summary': "Some of America's largest growth stocks struggled during the first half of 2026.",
   'pubDate': '2026-07-03T11:05:00Z',
   'displayTime': '2026-07-03T11:05:00Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/motleyfool.com/7beaf9e23b2bc6ca86cd02618f30e980',
    'originalWidth': 1400,
    'originalHeight': 700,
    'caption': 'A sculpture of a golden bull standing on a laptop computer.',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/HU1GH5bUKIQJV5ajdDPCSw--~B/aD03MDA7dz0xNDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/7beaf9e23b2bc6ca86cd02618f30e980',
      'width': 1400,
      'height': 700,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/wwFr12kJXYYWA3Mb2Jm1Pg--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/motleyfool.com/7beaf9e23b2bc6ca86cd02618f30e980',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Motley Fool',
    'url': 'http://www.fool.com/',
    'sourceId': 'motleyfool.com'},
   'canonicalUrl': {'url': 'https://www.fool.com/investing/2026/07/03/should-buy-invesco-qqq-etf-nasdaq-sell-off-answer/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/buy-invesco-qqq-etf-recent-110500285.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '008fa02c-a850-36be-b879-22c6e591169d',
  'content': {'id': '008fa02c-a850-36be-b879-22c6e591169d',
   'contentType': 'STORY',
   'title': 'The Next 30% Crash Will Happen. These 3 ETFs Mean You Won’t Panic-Sell at the Bottom',
   'description': '',
   'summary': 'History says it is coming. A 30% drawdown is part of the contract you signed when you bought stocks. What matters is whether you will still be holding the bag when prices recover. Three ETFs are built for that stress test: Schwab U.S. Dividend Equity ETF (NYSEARCA:SCHD) pays you to wait, iShares MSCI USA Min ... The Next 30% Crash Will Happen. These 3 ETFs Mean You Won’t Panic-Sell at the Bottom',
   'pubDate': '2026-07-02T23:29:50Z',
   'displayTime': '2026-07-02T23:29:50Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/24_7_wall_st__718/217303467a4890483ac937323e14d81c',
    'originalWidth': 1500,
    'originalHeight': 1000,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/XpwUTH_SvQb17AX5DAGeGg--~B/aD0xMDAwO3c9MTUwMDthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/24_7_wall_st__718/217303467a4890483ac937323e14d81c',
      'width': 1500,
      'height': 1000,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/QhfDycNuTxNbp2VFqXT6FA--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/24_7_wall_st__718/217303467a4890483ac937323e14d81c',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': '24/7 Wall St.',
    'url': 'https://247wallst.com/',
    'sourceId': '24_7_wall_st__718'},
   'canonicalUrl': {'url': 'https://247wallst.com/investing/etf/2026/07/02/the-next-30-crash-will-happen-these-3-etfs-mean-you-wont-panic-sell-at-the-bottom/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/options/articles/next-30-crash-happen-3-232950749.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '65faba3d-f494-3fb0-876c-7c9aaec3a84c',
  'content': {'id': '65faba3d-f494-3fb0-876c-7c9aaec3a84c',
   'contentType': 'STORY',
   'title': 'An Analyst Called SpaceX’s Valuation ‘Catastrophic.’ Options Traders Are Betting the Other Way',
   'description': '',
   'summary': 'CNBC’s Oliver Renick spent part of his July 2 segment on a tension defining SpaceX (NASDAQ:SPCX) trading. A Daiwa Securities analyst opened Thursday labeling the stock’s valuation “catastrophic”. Options desks spent the same morning buying calls. Shares are up roughly 9% off recent lows after a three-day bounce, closing at $157.54 on July 1 and ... An Analyst Called SpaceX’s Valuation ‘Catastrophic.’ Options Traders Are Betting the Other Way',
   'pubDate': '2026-07-02T19:36:35Z',
   'displayTime': '2026-07-02T19:36:35Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/24_7_wall_st__718/8da4835bbbd4abc67c1e3cab7908def0',
    'originalWidth': 1366,
    'originalHeight': 767,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/P2uxQYx3THMyuyvXY3wtGg--~B/aD03Njc7dz0xMzY2O2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/24_7_wall_st__718/8da4835bbbd4abc67c1e3cab7908def0',
      'width': 1366,
      'height': 767,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/920G_uGTD2NkzNqy1E5F0g--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/24_7_wall_st__718/8da4835bbbd4abc67c1e3cab7908def0',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': '24/7 Wall St.',
    'url': 'https://247wallst.com/',
    'sourceId': '24_7_wall_st__718'},
   'canonicalUrl': {'url': 'https://247wallst.com/investing/2026/07/02/an-analyst-called-spacexs-valuation-catastrophic-options-traders-are-betting-the-other-way/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/options/articles/analyst-called-spacex-valuation-catastrophic-193635828.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '3ebdbf20-ee67-3f12-bd58-b35745c26d7e',
  'content': {'id': '3ebdbf20-ee67-3f12-bd58-b35745c26d7e',
   'contentType': 'STORY',
   'title': 'Exchange-Traded Funds Fall, US Equities Mixed After Midday',
   'description': '',
   'summary': 'Broad Market Indicators Broad-market exchange-traded funds IWM and IVV fell. Actively traded I',
   'pubDate': '2026-07-02T17:16:19Z',
   'displayTime': '2026-07-02T17:16:19Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': None,
   'provider': {'displayName': 'MT Newswires',
    'url': 'https://www.mtnewswires.com/',
    'sourceId': 'mt_newswires_premium_news_706'},
   'canonicalUrl': {'url': 'https://finance.yahoo.com/markets/articles/exchange-traded-funds-fall-us-171619262.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/articles/exchange-traded-funds-fall-us-171619262.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': True,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '3f6ae920-61d7-35a7-a948-09efae76e776',
  'content': {'id': '3f6ae920-61d7-35a7-a948-09efae76e776',
   'contentType': 'STORY',
   'title': "Michael Burry's newest short reveals what really worries him about AI",
   'description': '',
   'summary': 'The AI trade isn’t just about Nvidia anymore. That could be the true warning sign underlying Michael Burry’s current move on the markets. The investor behind "The Big Short" has revealed new bearish positions against Tesla (TSLA), Nvidia (NVDA), Caterpillar (CAT), Applied Materials (AMAT), and the ...',
   'pubDate': '2026-07-02T17:07:00Z',
   'displayTime': '2026-07-02T17:07:00Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/thestreet_881/9c27139921c0ff44a59705c988be7bd1',
    'originalWidth': 3500,
    'originalHeight': 2333,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/qiaR4VeXpDRJIbJwbCGB0g--~B/aD0yMzMzO3c9MzUwMDthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/thestreet_881/9c27139921c0ff44a59705c988be7bd1',
      'width': 3500,
      'height': 2333,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/K2KHUSJD_4IjxL8sGe76.w--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/thestreet_881/9c27139921c0ff44a59705c988be7bd1',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'TheStreet',
    'url': 'https://www.thestreet.com/',
    'sourceId': 'thestreet_881'},
   'canonicalUrl': {'url': 'https://www.thestreet.com/investing/michael-burrys-newest-short-reveals-what-really-worries-him-about-ai',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/michael-burrys-newest-short-reveals-170700206.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '8998e084-b7af-3232-b189-6d4b514d6892',
  'content': {'id': '8998e084-b7af-3232-b189-6d4b514d6892',
   'contentType': 'STORY',
   'title': 'BLS Jobs Report: +57K, Half Expectations',
   'description': '',
   'summary': "This is the fourth-straight month of job growth from the BLS, which we haven't seen since the spring of 2025.",
   'pubDate': '2026-07-02T16:12:00Z',
   'displayTime': '2026-07-02T16:12:00Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': None,
   'provider': {'displayName': 'Zacks',
    'url': 'http://www.zacks.com/',
    'sourceId': 'zacks.com'},
   'canonicalUrl': {'url': 'https://finance.yahoo.com/economy/articles/bls-jobs-report-57k-half-161200954.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/economy/articles/bls-jobs-report-57k-half-161200954.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '2cbe791a-0de4-3801-9191-65a8198afa27',
  'content': {'id': '2cbe791a-0de4-3801-9191-65a8198afa27',
   'contentType': 'STORY',
   'title': 'The Mag 7 Just Lost $2.3 Trillion in a Single Month. Here’s the AI Fear Behind It',
   'description': '',
   'summary': 'The Magnificent 7 erased $2.3 trillion in market cap in June alone, the largest monthly loss ever for the group, even as the Nasdaq heads for its best quarter since 2020. CNBC’s MacKenzie Sigalos framed the split neatly on June 30: “the mag-7 erased 2.3 trillion in June alone, the largest monthly market cap loss ... The Mag 7 Just Lost $2.3 Trillion in a Single Month. Here’s the AI Fear Behind It',
   'pubDate': '2026-07-02T15:22:06Z',
   'displayTime': '2026-07-02T15:22:06Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/24_7_wall_st__718/c36d54274ba32baa3648ce360aef248a',
    'originalWidth': 1376,
    'originalHeight': 768,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/lZ083hrH3jyVgDGGBPkEAQ--~B/aD03Njg7dz0xMzc2O2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/24_7_wall_st__718/c36d54274ba32baa3648ce360aef248a',
      'width': 1376,
      'height': 768,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/BVPiOIdD4W8QFZzeRP_6bA--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/24_7_wall_st__718/c36d54274ba32baa3648ce360aef248a',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': '24/7 Wall St.',
    'url': 'https://247wallst.com/',
    'sourceId': '24_7_wall_st__718'},
   'canonicalUrl': {'url': 'https://247wallst.com/investing/2026/07/02/the-mag-7-just-lost-2-3-trillion-in-a-single-month-heres-the-ai-fear-behind-it/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/mag-7-just-lost-2-152206055.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '5801e17b-1c86-3efb-bbca-73ac3d4ba591',
  'content': {'id': '5801e17b-1c86-3efb-bbca-73ac3d4ba591',
   'contentType': 'STORY',
   'title': 'A Strategist Says Big Tech Is ‘Completely Underappreciated’ With a PEG Under 1 as Everyone Bails',
   'description': '',
   'summary': 'Venu Krishna went on CNBC’s Closing Bell Overtime on June 30 and argued that the money fleeing Big Tech is running the wrong direction. His pitch: a PEG ratio below 1 for the Mag 7 excluding Tesla, roughly 30% earnings growth in Q1, and multiples that have already been marked down. “Everybody, when they think ... A Strategist Says Big Tech Is ‘Completely Underappreciated’ With a PEG Under 1 as Everyone Bails',
   'pubDate': '2026-07-02T13:54:50Z',
   'displayTime': '2026-07-02T13:54:50Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/24_7_wall_st__718/32ded2fb95ce704a02a8585e36f78dca',
    'originalWidth': 2560,
    'originalHeight': 1534,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/ghDMKbv1DHRtsxIh_11ffw--~B/aD0xNTM0O3c9MjU2MDthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/24_7_wall_st__718/32ded2fb95ce704a02a8585e36f78dca',
      'width': 2560,
      'height': 1534,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/1jLSYYccxi8wg6mdTv.29w--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/24_7_wall_st__718/32ded2fb95ce704a02a8585e36f78dca',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': '24/7 Wall St.',
    'url': 'https://247wallst.com/',
    'sourceId': '24_7_wall_st__718'},
   'canonicalUrl': {'url': 'https://247wallst.com/investing/2026/07/02/a-strategist-says-big-tech-is-completely-underappreciated-with-a-peg-under-1-as-everyone-bails/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/strategist-says-big-tech-completely-135450089.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}}]

In [43]:
ticker.calendar

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for symbol: QQQ"}}}

{}

In [44]:
ticker.history(period="1mo")

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Capital Gains
Date,,,,,,,,
2026-06-03 00:00:00-04:00,746.489639,747.828195,740.196567,743.393066,40270200,0.000,0.0,0.0
2026-06-04 00:00:00-04:00,734.672624,742.683839,731.815778,739.796997,40782600,0.000,0.0,0.0
2026-06-05 00:00:00-04:00,729.258567,730.886782,703.546833,704.286011,99606600,0.000,0.0,0.0
2026-06-08 00:00:00-04:00,717.022016,722.236317,712.287229,715.283936,47401500,0.000,0.0,0.0
2026-06-09 00:00:00-04:00,722.186311,724.863361,685.616515,707.052979,91932200,0.000,0.0,0.0
2026-06-10 00:00:00-04:00,700.889750,710.499246,692.169352,692.928528,65334300,0.000,0.0,0.0
2026-06-11 00:00:00-04:00,698.522320,717.581391,694.237051,716.332764,71798900,0.000,0.0,0.0
2026-06-12 00:00:00-04:00,716.822210,723.215209,710.499203,720.548157,51168400,0.000,0.0,0.0
2026-06-15 00:00:00-04:00,737.289741,743.942464,736.570560,743.183289,46710200,0.000,0.0,0.0
2026-06-16 00:00:00-04:00,741.435190,743.402998,728.839048,729.058777,45348700,0.000,0.0,0.0
2026-06-17 00:00:00-04:00,734.382931,734.872383,720.058646,721.716858,51669300,0.000,0.0,0.0
2026-06-18 00:00:00-04:00,736.390778,741.005702,731.705924,739.807007,50154600,0.000,0.0,0.0
2026-06-22 00:00:00-04:00,742.020020,745.450012,734.390015,737.950012,43518600,0.813,0.0,0.0
2026-06-23 00:00:00-04:00,715.739990,723.609985,712.109985,713.650024,53354200,0.000,0.0,0.0
2026-06-24 00:00:00-04:00,715.369995,719.929993,704.450012,710.619995,52480400,0.000,0.0,0.0
2026-06-25 00:00:00-04:00,725.900024,726.830017,705.299988,716.380005,49668000,0.000,0.0,0.0
2026-06-26 00:00:00-04:00,707.130005,715.559998,702.809998,706.520020,47081800,0.000,0.0,0.0
2026-06-29 00:00:00-04:00,713.989990,724.580017,705.169983,724.080017,44939100,0.000,0.0,0.0
2026-06-30 00:00:00-04:00,724.179993,737.619995,723.909973,736.400024,42121800,0.000,0.0,0.0
2026-07-01 00:00:00-04:00,729.190002,731.919983,724.599976,725.169983,40803800,0.000,0.0,0.0
2026-07-02 00:00:00-04:00,725.580017,730.830017,707.559998,712.599976,50959800,0.000,0.0,0.0

ticker.history(period="1mo")

In [45]:
ticker.history(period="1y")

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Capital Gains
Date,,,,,,,,
2025-07-03 00:00:00-04:00,550.528548,554.529299,550.528548,553.553955,26443500,0.0,0.0,0.0
2025-07-07 00:00:00-04:00,550.866943,551.683020,546.945825,549.384094,45349300,0.0,0.0,0.0
2025-07-08 00:00:00-04:00,550.727559,551.354544,548.458458,549.692566,36153300,0.0,0.0,0.0
2025-07-09 00:00:00-04:00,551.822327,554.957253,550.448936,553.583862,43045500,0.0,0.0,0.0
2025-07-10 00:00:00-04:00,554.220759,554.628767,550.100588,552.787659,34710900,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
2026-06-26 00:00:00-04:00,707.130005,715.559998,702.809998,706.520020,47081800,0.0,0.0,0.0
2026-06-29 00:00:00-04:00,713.989990,724.580017,705.169983,724.080017,44939100,0.0,0.0,0.0
2026-06-30 00:00:00-04:00,724.179993,737.619995,723.909973,736.400024,42121800,0.0,0.0,0.0
2026-07-01 00:00:00-04:00,729.190002,731.919983,724.599976,725.169983,40803800,0.0,0.0,0.0
2026-07-02 00:00:00-04:00,725.580017,730.830017,707.559998,712.599976,50959800,0.0,0.0,0.0

In [46]:
ticker.funds_data.top_holdings

                              Name  Holding Percent
Symbol
NVDA                   NVIDIA Corp         0.081576
AAPL                     Apple Inc         0.072842
MSFT                Microsoft Corp         0.053153
MU           Micron Technology Inc         0.047964
AMZN                Amazon.com Inc         0.046192
AMD     Advanced Micro Devices Inc         0.036929
GOOGL         Alphabet Inc Class A         0.035201
TSLA                     Tesla Inc         0.034580
AVGO                  Broadcom Inc         0.033677
GOOG          Alphabet Inc Class C         0.032549

In [50]:
yf.Market("ASIA").summary

ASIA: Yahoo markettime endpoint does not support market='ASIA'; status data unavailable.

{'SHH': {'language': 'en-US',
  'region': 'US',
  'quoteType': 'INDEX',
  'typeDisp': 'Index',
  'quoteSourceName': 'Delayed Quote',
  'triggerable': False,
  'customPriceAlertConfidence': 'LOW',
  'hasPrePostMarketData': False,
  'firstTradeDateMilliseconds': 867807000000,
  'priceHint': 2,
  'regularMarketChange': 14.739502,
  'regularMarketChangePercent': 0.36584398,
  'regularMarketTime': 1783062029,
  'regularMarketPrice': 4043.6433,
  'regularMarketPreviousClose': 4112.44,
  'exchange': 'SHH',
  'market': 'cn_market',
  'fullExchangeName': 'Shanghai',
  'marketState': 'POSTPOST',
  'sourceInterval': 15,
  'exchangeDataDelayedBy': 15,
  'exchangeTimezoneName': 'Asia/Shanghai',
  'exchangeTimezoneShortName': 'CST',
  'gmtOffSetMilliseconds': 28800000,
  'esgPopulated': False,
  'tradeable': False,
  'cryptoTradeable': False,
  'shortName': 'SSE Composite Index',
  'symbol': '000001.SS'},
 'OSA': {'language': 'en-US',
  'region': 'US',
  'quoteType': 'INDEX',
  'typeDisp': 'Index',
  'quoteSourceName': 'Delayed Quote',
  'triggerable': False,
  'customPriceAlertConfidence': 'LOW',
  'hasPrePostMarketData': False,
  'firstTradeDateMilliseconds': -157420800000,
  'priceHint': 2,
  'regularMarketChange': 1010.9219,
  'regularMarketChangePercent': 1.4707923,
  'regularMarketTime': 1783061103,
  'regularMarketPrice': 69744.07,
  'regularMarketPreviousClose': 68733.15,
  'exchange': 'OSA',
  'market': 'jp_market',
  'fullExchangeName': 'Osaka',
  'marketState': 'POSTPOST',
  'sourceInterval': 20,
  'exchangeDataDelayedBy': 20,
  'exchangeTimezoneName': 'Asia/Tokyo',
  'exchangeTimezoneShortName': 'JST',
  'gmtOffSetMilliseconds': 32400000,
  'esgPopulated': False,
  'tradeable': False,
  'cryptoTradeable': False,
  'shortName': 'Nikkei 225',
  'symbol': '^N225'},
 'HKG': {'language': 'en-US',
  'region': 'US',
  'quoteType': 'INDEX',
  'typeDisp': 'Index',
  'quoteSourceName': 'Delayed Quote',
  'triggerable': False,
  'customPriceAlertConfidence': 'LOW',
  'hasPrePostMarketData': False,
  'firstTradeDateMilliseconds': 536376600000,
  'priceHint': 2,
  'regularMarketChange': 295.0,
  'regularMarketChangePercent': 1.2795473,
  'regularMarketTime': 1783066114,
  'regularMarketPrice': 23350.03,
  'regularMarketPreviousClose': 23055.03,
  'exchange': 'HKG',
  'market': 'hk_market',
  'fullExchangeName': 'HKSE',
  'marketState': 'POSTPOST',
  'sourceInterval': 15,
  'exchangeDataDelayedBy': 15,
  'exchangeTimezoneName': 'Asia/Hong_Kong',
  'exchangeTimezoneShortName': 'HKT',
  'gmtOffSetMilliseconds': 28800000,
  'esgPopulated': False,
  'tradeable': False,
  'cryptoTradeable': False,
  'shortName': 'Hang Seng',
  'symbol': '^HSI'},
 'ASX': {'language': 'en-US',
  'region': 'US',
  'quoteType': 'INDEX',
  'typeDisp': 'Index',
  'quoteSourceName': 'Delayed Quote',
  'triggerable': False,
  'customPriceAlertConfidence': 'LOW',
  'hasPrePostMarketData': False,
  'firstTradeDateMilliseconds': 722473200000,
  'priceHint': 2,
  'regularMarketChange': 119.90039,
  'regularMarketChangePercent': 1.3742952,
  'regularMarketTime': 1783062944,
  'regularMarketPrice': 8844.4,
  'regularMarketPreviousClose': 8724.5,
  'exchange': 'ASX',
  'market': 'au_market',
  'fullExchangeName': 'ASX',
  'marketState': 'POSTPOST',
  'sourceInterval': 20,
  'exchangeDataDelayedBy': 20,
  'exchangeTimezoneName': 'Australia/Sydney',
  'exchangeTimezoneShortName': 'AEST',
  'gmtOffSetMilliseconds': 36000000,
  'esgPopulated': False,
  'tradeable': False,
  'cryptoTradeable': False,
  'shortName': 'S&P/ASX 200 [XJO]',
  'symbol': '^AXJO'},
 'DJI': {'language': 'en-US',
  'region': 'US',
  'quoteType': 'INDEX',
  'typeDisp': 'Index',
  'quoteSourceName': 'Delayed Quote',
  'triggerable': False,
  'customPriceAlertConfidence': 'LOW',
  'hasPrePostMarketData': False,
  'priceHint': 2,
  'regularMarketChange': -66.049805,
  'regularMarketChangePercent': -1.0356449,
  'regularMarketTime': 1778260596,
  'regularMarketPrice': 6311.6,
  'regularMarketPreviousClose': 6377.65,
  'exchange': 'DJI',
  'market': 'us_market',
  'fullExchangeName': 'DJI',
  'marketState': 'CLOSED',
  'sourceInterval': 120,
  'exchangeDataDelayedBy': 0,
  'exchangeTimezoneName': 'America/New_York',
  'exchangeTimezoneShortName': 'EDT',
  'gmtOffSetMilliseconds': -14400000,
  'esgPopulated': False,
  'tradeable': False,
  'cryptoTradeable': False,
  'shortName': 'The Asia Dow (USD)',
  'symbol': '^ADOW'},
 'CCY': {'language': 'en-US',
  'region': 'US',
  'quoteType': 'CURRENCY',
  'typeDisp': 'Currency',
  'quoteSourceName': 'Delayed Quote',
  'triggerable': False,
  'customPriceAlertConfidence': 'LOW',
  'currency': 'JPY',
  'regularMarketChange': 0.10598755,
  'regularMarketChangePercent': 0.065789096,
  'regularMarketPrice': 161.204,
  'regularMarketPreviousClose': 161.098,
  'shortName': 'USD/JPY',
  'hasPrePostMarketData': False,
  'firstTradeDateMilliseconds': 846633600000,
  'priceHint': 4,
  'regularMarketTime': 1783085253,
  'exchange': 'CCY',
  'market': 'ccy_market',
  'fullExchangeName': 'CCY',
  'marketState': 'REGULAR',
  'sourceInterval': 15,
  'exchangeDataDelayedBy': 0,
  'exchangeTimezoneName': 'Europe/London',
  'exchangeTimezoneShortName': 'BST',
  'gmtOffSetMilliseconds': 3600000,
  'esgPopulated': False,
  'tradeable': False,
  'cryptoTradeable': False,
  'symbol': 'JPY=X'}}